name: Water plants ping

on:
  schedule:
    # GitHub Actions uses UTC. 07:00 UTC ≈ 09:00 in Europe/Prague (CET/CEST aware).
    - cron: "0 7 * * 1,4"  # Mondays & Thursdays at 09:00 Prague local time
  workflow_dispatch: {}     # allow manual trigger

jobs:
  post-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Post Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WATER_WEBHOOK }}
        run: |
          payload='{"content":"🌿 Friendly reminder: did anyone water the plants today? Please react ✅ if done."}'
          curl -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK"
